# Generated by Django 5.2.9 on 2026-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_remove_testimonial_role_testimonial_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark this testimonial as featured'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='program',
            field=models.CharField(blank=True, help_text='Optional: Program name related to this testimonial', max_length=200),
        ),
    ]
