# Generated by Django 5.2.11 on 2026-03-08 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_alter_testimonial_options_testimonial_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-featured', '-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(blank=True, help_text='Designation or role of the person', max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide testimonial from website'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='message',
            field=models.TextField(help_text='Testimonial message or feedback'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(help_text='Name of the person giving the testimonial', max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo of the person', null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5, help_text='Rating given by the person (1 to 5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
