# Generated by Django 5.2.9 on 2026-02-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprogram',
            name='guests',
            field=models.TextField(blank=True, help_text='Enter Chief Guest and other guests. Add each guest on a new line.', null=True),
        ),
        migrations.AddField(
            model_name='healthprogram',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprogram',
            name='total_beneficiaries',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
