# Generated by Django 5.2.9 on 2026-02-19 17:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_healthprogram_guests_healthprogram_objective_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthprogram',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='healthprogram',
            name='image',
        ),
        migrations.AddField(
            model_name='healthprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HealthProgramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='health/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='health.healthprogram')),
            ],
        ),
    ]
