# Generated by Django 5.2.11 on 2026-03-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_leadership',
            field=models.BooleanField(default=False, help_text='Enable this for CEO / Founder / Leadership members'),
        ),
        migrations.AddField(
            model_name='member',
            name='message',
            field=models.TextField(blank=True, help_text='Leadership message such as CEO or Founder message', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography of the member', null=True),
        ),
    ]
