# Generated by Django 5.2.11 on 2026-03-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_is_leadership_member_message_alter_member_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-is_leadership', 'display_order', 'id'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='member',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls the order of members on the website (lower number appears first)'),
        ),
    ]
