# Generated by Django 5.2.11 on 2026-03-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_options_member_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='designation',
            field=models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('vice_secretary', 'Vice Secretary'), ('treasurer', 'Treasurer'), ('member', 'Member'), ('ceo', 'CEO'), ('volunteer', 'Volunteer'), ('donor', 'Donor')], help_text='Select the role of the member in the NGO', max_length=50),
        ),
    ]
