# Generated by Django 5.2.9 on 2026-01-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGOProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('map_link', models.URLField(blank=True)),
                ('about', models.TextField()),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('objectives', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NGO Profile',
                'verbose_name_plural': 'NGO Profile',
            },
        ),
    ]
