# Generated by Django 5.2.9 on 2026-01-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngoprofile',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
