# Generated by Django 5.2.9 on 2026-02-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ngoprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='established_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='governing_body_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='legal_identity',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
