# Generated by Django 5.2.9 on 2026-02-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ngoprofile_established_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngoprofile',
            old_name='location',
            new_name='registered_location',
        ),
        migrations.RemoveField(
            model_name='ngoprofile',
            name='established_year',
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='established_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
