# Generated by Django 5.2.9 on 2026-02-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_location_ngoprofile_registered_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100)),
                ('established_date', models.DateField()),
                ('legal_identity', models.TextField()),
                ('registered_location', models.CharField(max_length=200)),
                ('office_address', models.TextField()),
                ('mobile_number_1', models.CharField(max_length=15)),
                ('mobile_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_number_3', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organization Detail',
                'verbose_name_plural': 'Organization Details',
            },
        ),
    ]
