# Generated by Django 5.2.11 on 2026-03-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organizationdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ngoprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'NGO Profile', 'verbose_name_plural': 'NGO Profiles'},
        ),
        migrations.AlterModelOptions(
            name='organizationdetails',
            options={'ordering': ['-created_at'], 'verbose_name': 'Organization Detail', 'verbose_name_plural': 'Organization Details'},
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ngo/logo/'),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organizationdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
