# Generated by Django 5.2.11 on 2026-03-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ngoprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngoprofile',
            name='name',
            field=models.CharField(default='Shri Ramakrishna Vivekananda Jnana Vikasa Shikshana Samste', max_length=255),
        ),
    ]
