# Generated by Django 5.2.9 on 2026-02-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_remove_environmentactivity_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentactivity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='environmentactivity',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentactivity',
            name='supporting_organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentactivity',
            name='total_beneficiaries',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
