# Generated by Django 5.2.9 on 2026-02-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_environmentactivity_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmentactivity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='environmentactivityimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='environmentactivityimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='environment/'),
        ),
    ]
