# Generated by Django 5.2.11 on 2026-03-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-date'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AddField(
            model_name='program',
            name='sponsors',
            field=models.TextField(blank=True, help_text='List supporting organizations separated by commas or new lines', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='total_beneficiaries',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='volunteers_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('pre_primary', 'Pre-Primary School'), ('learning_hub', 'Ramakrishna Learning Hub'), ('health_awareness', 'Health Camps & Awareness'), ('organic_plantation', 'Organic / Plantation Initiatives'), ('cultural_events', 'Cultural / National Events')], max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
