# Generated by Django 5.2.9 on 2026-01-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('environment', 'Environment'), ('events', 'Events'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
