# Generated by Django 5.2.9 on 2026-02-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryimage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('education', 'Education Program'), ('health', 'Health Camp'), ('environment', 'Environment / Plantation'), ('events', 'Events & Celebration'), ('general', 'General Activities')], default='general', max_length=50),
        ),
    ]
